csv_folder: ./lib/cr-csv/assets/tilemaps
pdf_folder: ./dst

tilemaps:
  - tilemap
  - tilemap_2v2
  - tilemap_pve
  - tilemap_pve1
  - tilemap_touchdown
  - tilemap_touchdown_2v2
  - tilemap_tve

openfile: True

